### 01. Environment Setup

In [37]:
#Import libraries
import pandas as pd
import numpy as np
import os

In [38]:
path = r'/Users/Cel/Documents/Data Analytics/09-2023 Instacart Basket Analysis'

In [39]:
#Import file
ords_prods_merged = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_grouped_data.pkl'))

In [29]:
#Check shape
ords_prods_merged.shape

(32404859, 24)

In [30]:
#Check columns
ords_prods_merged.head()

,order_id,user_id,number_of_orders,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,price_range_loc,busiest_period_of_day,busiest_day,two_busiest_days,max_order,loyalty_flag,average_spend,spending_category,median_days_since_prior_order,order_frequency
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,Mid-range product,Average orders,Regularly busy,Regularly busy,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,Mid-range product,Average orders,Regularly busy,Least busy days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Least busy days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,Mid-range product,Average orders,Least busy,Least busy days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,Mid-range product,Most orders,Least busy,Least busy days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer

In [ ]:
ords_prods_merged['median_days_since_prior_order'].value_counts(dropna = False)

### 02. Number of orders by department_id

In [6]:
#Find aggregated mean of 'number_of_orders' by 'department_id' for entire df
ords_prods_merged.groupby('department_id').agg({'number_of_orders': ['mean']})

              number_of_orders
                          mean
department_id
1                    15.457838
2                    17.277920
3                    17.170395
4                    17.811403
5                    15.215751
6                    16.439806
7                    17.225802
8                    15.340650
9                    15.895474
10                   20.197148
11                   16.170638
12                   15.887671
13                   16.583536
14                   16.773669
15                   16.165037
16                   17.665606
17                   15.694469
18                   19.310397
19                   17.177343
20                   16.473447
21                   22.902379

The output is quite different than that of the subset. It includes all the department ids (there were only 8 in the subset), and the means by department id have also changed slightly.

### 03. Loyalty flag for customers *See other notebook for exercise work

In [7]:
ords_prods_merged[['user_id', 'loyalty_flag', 'number_of_orders']].head()

   user_id  loyalty_flag  number_of_orders
0        1  New customer                 1
1        1  New customer                 2
2        1  New customer                 3
3        1  New customer                 4
4        1  New customer                 5

### 04. Product prices for loyalty categories

In [8]:
#Compare basic product price statistics between loyalty categories
ords_prods_merged.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

### 05. Derive 'spending_category' column

In [9]:
#Create new column 'average_spend' - aggregate order price per user_id
ords_prods_merged['average_spend'] = ords_prods_merged.groupby(['user_id'])['prices'].transform(np.mean)

In [16]:
ords_prods_merged

,order_id,user_id,number_of_orders,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,department_id,prices,_merge,price_range_loc,busiest_period_of_day,busiest_day,two_busiest_days,max_order,loyalty_flag,average_spend
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,7,9.0,both,Mid-range product,Average orders,Regularly busy,Regularly busy,10,New customer,6.367797
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Average orders,Regularly busy,Least busy days,10,New customer,6.367797
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Most orders,Regularly busy,Least busy days,10,New customer,6.367797
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Average orders,Least busy,Least busy days,10,New customer,6.367797
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Most orders,Least busy,Least busy days,10,New customer,6.367797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32404854,1320836,202557,17,2,15,1.0,43553,2,1,Orange Energy Shots,...,7,3.7,both,Low-range product,Most orders,Regularly busy,Regularly busy,31,Regular customer,6.905655
32404855,31526,202557,18,5,11,3.0,43553,2,1,Orange Energy Shots,...,7,3.7,both,Low-range product,Most orders,Regularly busy,Regularly busy,31,Regular customer,6.905655
32404856,758936,203436,1,2,7,NaN,42338,4,0,"Zucchini Chips, Pesto",...,19,6.9,both,Mid-range product,Average orders,Regularly busy,Regularly busy,3,New customer,7.631579
32404857,2745165,203436,2,3,5,15.0,42338,16,1,"Zucchini Chips, Pesto",...,19,6.9,both,Mid-range product,Fewest orders,Regularly busy,Least busy days,3,New customer,7.631579
32404858,3093936,205420,1,4,14,NaN,28818,8,0,Hot Oatmeal Multigrain Raisin,...,14,10.3,both,Mid-range product,Most orders,Least busy,Least busy days,16,Regular customer,7.684746

In [10]:
#Create a flag that assigns spending category based on 'average_spend'
ords_prods_merged.loc[ords_prods_merged['average_spend'] < 10, 'spending_category'] = 'Low spender'

In [11]:
ords_prods_merged.loc[ords_prods_merged['average_spend'] >= 10, 'spending_category'] = 'High spender'

In [12]:
#Check category frequencies
ords_prods_merged['spending_category'].value_counts(dropna = False)

spending_category
Low spender     31770614
High spender      634245
Name: count, dtype: int64

### 06. Derive 'order_frequency' column

In [13]:
#Create new column 'median_days_since_prior_order'
ords_prods_merged['median_days_since_prior_order'] = ords_prods_merged.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [22]:
ords_prods_merged.head(60)

,order_id,user_id,number_of_orders,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,_merge,price_range_loc,busiest_period_of_day,busiest_day,two_busiest_days,max_order,loyalty_flag,average_spend,spending_category,median_days_since_prior_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,both,Mid-range product,Average orders,Regularly busy,Regularly busy,10,New customer,6.367797,Low spender,20.5
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,both,Mid-range product,Average orders,Regularly busy,Least busy days,10,New customer,6.367797,Low spender,20.5
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Least busy days,10,New customer,6.367797,Low spender,20.5
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,both,Mid-range product,Average orders,Least busy,Least busy days,10,New customer,6.367797,Low spender,20.5
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Least busy,Least busy days,10,New customer,6.367797,Low spender,20.5
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,both,Mid-range product,Average orders,Regularly busy,Regularly busy,10,New customer,6.367797,Low spender,20.5
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,10,New customer,6.367797,Low spender,20.5
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,10,New customer,6.367797,Low spender,20.5
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,10,New customer,6.367797,Low spender,20.5
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,both,Mid-range product,Average orders,Least busy,Least busy days,10,New customer,6.367797,Low spender,20.5
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,22,Regular customer,3.980556,Low spender,10.0
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,22,Regular customer,3.980556,Low spender,10.0
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,22,Regular customer,3.980556,Low spender,10.0
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,22,Regular customer,3.980556,Low spender,10.0
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,22,Regular customer,3.980556,Low spender,10.0
15,2293453,19,2,5,14,6.0,196,3,0,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,9,New customer,8.372059,Low spender,6.0
16,1973799,19,5,6,12,8.0,196,15,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,9,New customer,8.372059,Low spender,6.0
17,532817,19,7,4,17,6.0,196,1,1,Soda,...,both,Mid-range product,Average orders,Least busy,Least busy days,9,New customer,8.372059,Low spender,6.0
18,1573906,21,10,3,10,6.0,196,2,0,Soda,...,both,Mid-range product,Most orders,Regularly busy,Least busy days,33,Regular customer,7.012683,Low spender,7.5
19,1593000,31,10,3,8,7.0,196,17,0,Soda,...,both,Mid-range product,Average orders,Regularly busy,Least busy days,20,Regular customer,8.137793,Low spender,6.0
20,2231262,31,17,3,11,8.0,196,14,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Least busy days,20,Regular customer,8.137793,Low spender,6.0
21,2580647,43,6,4,16,4.0,196,9,0,Soda,...,both,Mid-range product,Most orders,Least busy,Least busy days,11,Regular customer,7.444898,Low spender,10.0
22,2187180,43,9,4,12,3.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Least busy,Least busy days,11,Regular customer,7.444898,Low spender,10.0
23,2497897,52,1,1,9,NaN,196,4,0,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,27,Regular customer,6.356287,Low spender,8.0
24,1318871,52,2,1,10,7.0,196,5,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,27,Regular customer,6.356287,Low spender,8.0
25,1261384,52,3,1,10,7.0,196,3,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,27,Regular customer,6.356287,Low spender,8.0
26,580568,52,5,2,10,8.0,196,6,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0
27,2428073,52,7,2,7,8.0,196,5,1,Soda,...,both,Mid-range product,Average orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0
28,342306,52,9,1,11,7.0,196,5,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,27,Regular customer,6.356287,Low spender,8.0
29,1520353,52,10,2,10,8.0,196,4,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0
30,2542086,52,11,2,9,7.0,196,3,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0
31,944694,52,12,1,16,6.0,196,7,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,27,Regular customer,6.356287,Low spender,8.0
32,1268191,52,15,2,11,8.0,196,3,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0
33,1122089,52,17,2,10,6.0,196,4,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0
34,1498922,52,18,2,10,14.0,196,6,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0
35,180919,52,19,3,8,8.0,196,4,1,Soda,...,both,Mid-range product,Average orders,Regularly busy,Least busy days,27,Regular customer,6.356287,Low spender,8.0
36,2695875,52,21,5,10,30.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0
37,3205960,67,1,3,11,NaN,196,1,0,Soda,...,both,Mid-range product,Most orders,Regularly busy,Least busy days,24,Regular customer,7.656790,Low spender,7.0
38,970922,67,2,1,15,5.0,196,2,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0
39,596585,67,3,1,13,7.0,196,2,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0
40,2037087,67,4,2,9,8.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,24,Regular customer,7.656790,Low spender,7.0
41,2474111,67,5,3,14,8.0,196,2,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Least busy days,24,Regular customer,7.656790,Low spender,7.0
42,1568481,67,6,3,12,7.0,196,2,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Least busy days,24,Regular customer,7.656790,Low spender,7.0
43,2048527,67,8,2,11,7.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,24,Regular customer,7.656790,Low spender,7.0
44,2389031,67,9,2,14,7.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,24,Regular customer,7.656790,Low spender,7.0
45,2378562,67,10,1,10,6.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0
46,1515698,67,11,1,11,7.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0
47,1928050,67,12,2,12,8.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,24,Regular customer,7.656790,Low spender,7.0
48,1949274,67,13,1,10,6.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0
49,551869,67,14,1,9,7.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0
50,768572,67,16,4,10,9.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Least busy,Least busy days,24,Regular customer,7.656790,Low spender,7.0
51,150528,67,18,5,16,4.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,24,Regular customer,7.656790,Low spender,7.0
52,29758,67,19,0,14,9.0,196,2,1,Soda,...,both,Mid-range product,Most orders,Busiest day,Busiest days,24,Regular customer,7.656790,Low spender,7.0
53,1558976,67,21,1,9,5.0,196,2,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0
54,863974,67,22,1,11,14.0,196,3,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0
55,2308399,67,23,1,14,14.0,196,1,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0
56,2759128,81,3,1,9,14.0,196,2,0,Soda,...,both,Mid-range product,Most orders,Regularly busy,Busiest days,7,New customer,8.165385,Low spender,30.0
57,1812985,81,5,2,20,30.0,196,1,1,Soda,...,both,Mid-range product,Average orders,Regularly busy,Regularly busy,7,New customer,8.165385,Low spender,30.0
58,1889835,82,1,3,15,NaN,196,6,0,Soda,...,both,Mid-range product,Most orders,Regularly busy,Least busy days,19,Regular customer,6.441221,Low spender,11.5
59,499460,82,3,5,10,5.0,196,2,1,Soda,...,both,Mid-range product,Most orders,Regularly busy,Regularly busy,19,Regular customer,6.441221,Low spender,11.5

In [14]:
#Create a flag that assigns order frequency based on 'median_days_since_prior_order'
ords_prods_merged.loc[ords_prods_merged['median_days_since_prior_order'] > 20, 'order_frequency'] = 'Non-frequent customer'

In [15]:
ords_prods_merged.loc[(ords_prods_merged['median_days_since_prior_order'] > 10) & (ords_prods_merged['median_days_since_prior_order'] <= 20), 'order_frequency'] = 'Regular customer'

In [16]:
ords_prods_merged.loc[ords_prods_merged['median_days_since_prior_order'] <=10, 'order_frequency'] = 'Frequent customer'

In [17]:
ords_prods_merged.head(60)

,order_id,user_id,number_of_orders,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,price_range_loc,busiest_period_of_day,busiest_day,two_busiest_days,max_order,loyalty_flag,average_spend,spending_category,median_days_since_prior_order,order_frequency
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,Mid-range product,Average orders,Regularly busy,Regularly busy,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,Mid-range product,Average orders,Regularly busy,Least busy days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Least busy days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,Mid-range product,Average orders,Least busy,Least busy days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,Mid-range product,Most orders,Least busy,Least busy days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,Mid-range product,Average orders,Regularly busy,Regularly busy,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,Mid-range product,Average orders,Least busy,Least busy days,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
15,2293453,19,2,5,14,6.0,196,3,0,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,9,New customer,8.372059,Low spender,6.0,Frequent customer
16,1973799,19,5,6,12,8.0,196,15,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,9,New customer,8.372059,Low spender,6.0,Frequent customer
17,532817,19,7,4,17,6.0,196,1,1,Soda,...,Mid-range product,Average orders,Least busy,Least busy days,9,New customer,8.372059,Low spender,6.0,Frequent customer
18,1573906,21,10,3,10,6.0,196,2,0,Soda,...,Mid-range product,Most orders,Regularly busy,Least busy days,33,Regular customer,7.012683,Low spender,7.5,Frequent customer
19,1593000,31,10,3,8,7.0,196,17,0,Soda,...,Mid-range product,Average orders,Regularly busy,Least busy days,20,Regular customer,8.137793,Low spender,6.0,Frequent customer
20,2231262,31,17,3,11,8.0,196,14,1,Soda,...,Mid-range product,Most orders,Regularly busy,Least busy days,20,Regular customer,8.137793,Low spender,6.0,Frequent customer
21,2580647,43,6,4,16,4.0,196,9,0,Soda,...,Mid-range product,Most orders,Least busy,Least busy days,11,Regular customer,7.444898,Low spender,10.0,Frequent customer
22,2187180,43,9,4,12,3.0,196,1,1,Soda,...,Mid-range product,Most orders,Least busy,Least busy days,11,Regular customer,7.444898,Low spender,10.0,Frequent customer
23,2497897,52,1,1,9,NaN,196,4,0,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
24,1318871,52,2,1,10,7.0,196,5,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
25,1261384,52,3,1,10,7.0,196,3,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
26,580568,52,5,2,10,8.0,196,6,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
27,2428073,52,7,2,7,8.0,196,5,1,Soda,...,Mid-range product,Average orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
28,342306,52,9,1,11,7.0,196,5,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
29,1520353,52,10,2,10,8.0,196,4,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
30,2542086,52,11,2,9,7.0,196,3,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
31,944694,52,12,1,16,6.0,196,7,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
32,1268191,52,15,2,11,8.0,196,3,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
33,1122089,52,17,2,10,6.0,196,4,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
34,1498922,52,18,2,10,14.0,196,6,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
35,180919,52,19,3,8,8.0,196,4,1,Soda,...,Mid-range product,Average orders,Regularly busy,Least busy days,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
36,2695875,52,21,5,10,30.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
37,3205960,67,1,3,11,NaN,196,1,0,Soda,...,Mid-range product,Most orders,Regularly busy,Least busy days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
38,970922,67,2,1,15,5.0,196,2,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
39,596585,67,3,1,13,7.0,196,2,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
40,2037087,67,4,2,9,8.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
41,2474111,67,5,3,14,8.0,196,2,1,Soda,...,Mid-range product,Most orders,Regularly busy,Least busy days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
42,1568481,67,6,3,12,7.0,196,2,1,Soda,...,Mid-range product,Most orders,Regularly busy,Least busy days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
43,2048527,67,8,2,11,7.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
44,2389031,67,9,2,14,7.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
45,2378562,67,10,1,10,6.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
46,1515698,67,11,1,11,7.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
47,1928050,67,12,2,12,8.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
48,1949274,67,13,1,10,6.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
49,551869,67,14,1,9,7.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
50,768572,67,16,4,10,9.0,196,1,1,Soda,...,Mid-range product,Most orders,Least busy,Least busy days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
51,150528,67,18,5,16,4.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
52,29758,67,19,0,14,9.0,196,2,1,Soda,...,Mid-range product,Most orders,Busiest day,Busiest days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
53,1558976,67,21,1,9,5.0,196,2,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
54,863974,67,22,1,11,14.0,196,3,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
55,2308399,67,23,1,14,14.0,196,1,1,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
56,2759128,81,3,1,9,14.0,196,2,0,Soda,...,Mid-range product,Most orders,Regularly busy,Busiest days,7,New customer,8.165385,Low spender,30.0,Non-frequent customer
57,1812985,81,5,2,20,30.0,196,1,1,Soda,...,Mid-range product,Average orders,Regularly busy,Regularly busy,7,New customer,8.165385,Low spender,30.0,Non-frequent customer
58,1889835,82,1,3,15,NaN,196,6,0,Soda,...,Mid-range product,Most orders,Regularly busy,Least busy days,19,Regular customer,6.441221,Low spender,11.5,Regular customer
59,499460,82,3,5,10,5.0,196,2,1,Soda,...,Mid-range product,Most orders,Regularly busy,Regularly busy,19,Regular customer,6.441221,Low spender,11.5,Regular customer

In [18]:
#Check frequency counts
ords_prods_merged['order_frequency'].value_counts(dropna = False)

order_frequency
Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: count, dtype: int64

### 07. Export file

In [28]:
#Export to pickle
ords_prods_merged.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_grouped_data.pkl'))